"""Add Review Model

Revision ID: 21d85d4110f8
Revises: b86fc45a0a67
Create Date: 2023-10-22 19:46:18.240197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d85d4110f8'
down_revision = 'b86fc45a0a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
