"""Add Review Model

Revision ID: f376b9fde87d
Revises: 21d85d4110f8
Create Date: 2023-10-22 20:04:01.669540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f376b9fde87d'
down_revision = '21d85d4110f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
